import React, { useMemo } from 'react'
import { ArrowUpRight, CheckCircle2, AlertTriangle, Timer, Wrench, CalendarRange, Gauge, Activity, Clock3, ShieldCheck, PackageSearch, ClipboardCheck } from '../icons.jsx'
import { Badge, Empty } from '../components/UI.jsx'
import { fmtDateTime, isoDate, addDays, mondayOf, kpiTone, shortStatusLabel } from '../lib/utils.js'
import { periodRepairMetrics, tpmMetrics, pmMetrics, defectMetrics, topLossMachines } from '../lib/kpi.js'

export default function Dashboard({jobs,repairs,findings,inspections,pmSchedule,kpiSettings,machines,onGo,onEditGroup}){
  const today=new Date(), from=isoDate(addDays(today,-29)), to=isoDate(today),weekStart=isoDate(mondayOf(today)),weekEnd=isoDate(addDays(new Date(weekStart+'T00:00:00'),6))
  const cfg=kpiSettings?.find(x=>x.machine_no==null)||kpiSettings?.[0]||{}
  const repair=useMemo(()=>periodRepairMetrics({repairs,machines,from,to,hoursPerDay:cfg.hours_per_day||24}),[repairs,machines,from,to,cfg.hours_per_day])
  const tpmWeek=useMemo(()=>tpmMetrics(jobs,weekStart,weekEnd),[jobs,weekStart,weekEnd]);const pm=useMemo(()=>pmMetrics(pmSchedule,from,to),[pmSchedule,from,to]);const defect=useMemo(()=>defectMetrics(findings,from,to),[findings,from,to]);const topLoss=useMemo(()=>topLossMachines(repair.rows,6),[repair.rows])
  const efficiencyLabel=machines.length>1?'Maintenance Efficiency':'Availability';const efficiencyTh=machines.length>1?'ประสิทธิภาพเวลาหลังหัก Breakdown Loss':'ความพร้อมใช้งานของเครื่อง';const efficiencyTarget=machines.length>1?`Fleet availability ${repair.fleetAvailability.toFixed(2)}%`:`Target ${cfg.target_availability??95}%`;
  const latestInspections=inspections.slice(0,5);const grouped=useMemo(()=>{const m=new Map();tpmWeek.rows.forEach(j=>{const id=j.plan_group_id||j.id;if(!m.has(id))m.set(id,[]);m.get(id).push(j)});return [...m.entries()].slice(0,4)},[tpmWeek.rows]);const openFindings=findings.filter(f=>f.status!=='closed')
  return <>
    <section className="executive-kpi-grid"><Metric label="MTBF · 30 days" th="ระยะห่างระหว่างการซ่อม" value={repair.mtbf!==null?`${repair.mtbf.toFixed(1)} h`:'N/A'} icon={Activity} tone={kpiTone(repair.mtbf,cfg.target_mtbf_hr,'high')} target={cfg.target_mtbf_hr&&`Target ${cfg.target_mtbf_hr} h`}/><Metric label="MTTR · 30 days" th="เวลาซ่อมเฉลี่ย" value={`${repair.mttr.toFixed(0)} min`} icon={Clock3} tone={kpiTone(repair.mttr,cfg.target_mttr_min,'low')} target={cfg.target_mttr_min&&`Target ≤ ${cfg.target_mttr_min} min`}/><Metric label={efficiencyLabel} th={efficiencyTh} value={`${repair.availability.toFixed(2)}%`} icon={Gauge} tone={kpiTone(repair.availability,cfg.target_availability,'high')} target={efficiencyTarget}/><Metric label="TPM Completion" th="ทำแผน TPM สัปดาห์นี้" value={`${tpmWeek.completion}%`} icon={CheckCircle2} tone={kpiTone(tpmWeek.completion,cfg.target_tpm_completion,'high')} target={`${tpmWeek.completed}/${tpmWeek.rows.length} jobs`} progress={tpmWeek.completion}/><Metric label="PM Compliance" th="PM ตรงกำหนด" value={`${pm.compliance}%`} icon={ShieldCheck} tone={kpiTone(pm.compliance,cfg.target_pm_compliance,'high')} target={`${pm.completed}/${pm.due.length} due`} progress={pm.compliance}/><Metric label="Loss Time · 30 days" th="Loss งานซ่อม" value={`${repair.lossMin.toLocaleString()} min`} icon={Timer} tone="red" target={`${repair.breakdowns} repair records`}/></section>
    <section className="quick-status-strip"><button onClick={()=>onGo('defects')}><AlertTriangle/><span><b>{defect.open}</b> Open defects<small>Defect / Finding ค้าง</small></span></button><button onClick={()=>onGo('spares')}><PackageSearch/><span><b>{defect.waitingSpare}</b> Waiting spare<small>งานรออะไหล่</small></span></button><button onClick={()=>onGo('inspection')}><ClipboardCheck/><span><b>{latestInspections.length?latestInspections[0].overall_status==='abnormal'?'!':'✓':'-'}</b> Latest condition<small>Inspection ล่าสุด</small></span></button><button onClick={()=>onGo('pm')}><CalendarRange/><span><b>{pm.overdue}</b> PM overdue<small>PM เกินกำหนด</small></span></button></section>
    <section className="dashboard-layout"><article className="card span-2"><CardHead title="This Week TPM Plan" th="แผน TPM สัปดาห์นี้" sub="One plan group can contain multiple machines." action={()=>onGo('weekly')}/>{grouped.length?<div className="mini-plan-list">{grouped.map(([id,items])=><MiniPlan key={id} id={id} items={items} onEditGroup={onEditGroup}/>)}</div>:<Empty title="No plan this week" text="ยังไม่มีแผนสัปดาห์นี้"/>}</article><article className="card"><CardHead title="Top Loss · 30 days" th="เครื่อง Loss สูง" sub="From Repair History" action={()=>onGo('kpi')}/>{topLoss.length?<div className="loss-list loss-list-rich">{topLoss.map((x,i)=><div key={x.machine}><span className="rank-no">{i+1}</span><div className="grow"><b>{x.machine}</b><small>{x.topIssue} · {x.count} repairs</small></div><strong>{x.loss.toLocaleString()} min</strong></div>)}</div>:<Empty/>}</article><article className="card"><CardHead title="Urgent Follow-up" th="งานติดตามเร่งด่วน" sub="Defect / Follow-up" action={()=>onGo('followup')}/>{openFindings.length?<div className="follow-mini">{openFindings.slice(0,6).map(f=><div key={f.id}><div><b>{f.machines?.machine_no||'-'}</b><span>{f.finding}</span></div><Badge tone={f.status==='waiting_spare'?'amber':f.priority==='A'?'red':'neutral'}>{shortStatusLabel(f.status)}</Badge></div>)}</div>:<Empty title="No open follow-up" text="ไม่มีงานค้าง"/>}</article><article className="card"><CardHead title="Latest Condition" th="สภาพเครื่องล่าสุด" sub="Inspection" action={()=>onGo('inspection')}/>{latestInspections.length?<div className="condition-mini">{latestInspections.map(i=><div key={i.id}><div className={`condition-dot ${i.overall_status}`}/><div className="grow"><b>{i.machines?.machine_no||'-'}</b><span>{fmtDateTime(i.completed_at||i.created_at)}</span></div><Badge tone={i.overall_status==='abnormal'?'red':i.overall_status==='watch'?'amber':'green'}>{i.condition_score??'-'}%</Badge></div>)}</div>:<Empty title="No inspection yet" text="ยังไม่มี Inspection"/>}</article><article className="card span-2"><CardHead title="Latest Repairs" th="งานซ่อมล่าสุด" sub="Repair History · MPR database" action={()=>onGo('repairs')}/>{repairs.length?<div className="repair-list-pro">{repairs.slice(0,6).map(r=><div key={r.id}><div className="repair-icon"><Wrench size={17}/></div><div className="grow"><b>{r.machine_no_snapshot} · {r.symptom}</b><span>{fmtDateTime(r.started_at)} · {r.technician_name_snapshot||'-'}</span></div><strong>{Number(r.loss_time_min)||0} min</strong></div>)}</div>:<Empty/>}</article></section>
  </>
}
function Metric({label,th,value,icon:Icon,tone='blue',target,progress}){return <article className={`metric-card metric-${tone}`}><div className="metric-top"><span>{label}<small>{th}</small></span><div className={`metric-icon ${tone}`}><Icon size={18}/></div></div><strong>{value}</strong>{progress!==undefined&&<div className="metric-progress"><i style={{width:`${Math.min(100,Math.max(0,progress))}%`}}/></div>}<small>{target||'Target not set · ยังไม่ได้ตั้งเป้า'}</small></article>}
function CardHead({title,th,sub,action}){return <header className="card-head"><div><h3>{title}</h3><span>{th}</span><p>{sub}</p></div>{action&&<button onClick={action}>View all <small>ดูทั้งหมด</small> <ArrowUpRight size={15}/></button>}</header>}
function MiniPlan({id,items,onEditGroup}){const done=items.filter(j=>['completed','partial'].includes(j.job_status)).length;const first=items[0];return <div className="mini-plan"><div className="date-tile"><strong>{new Date(first.planned_date+'T00:00:00').getDate()}</strong><span>{new Intl.DateTimeFormat('en',{month:'short'}).format(new Date(first.planned_date+'T00:00:00'))}</span></div><div className="grow"><div className="plan-title-row"><b>{first.plan_group_name||'TPM Plan'}</b><Badge tone={done===items.length?'green':'blue'}>{done}/{items.length}</Badge></div><span>{new Set(items.map(x=>x.machine_id)).size} machines · {items.reduce((s,j)=>s+(Number(j.planned_stop_min)||0),0)} min</span><div className="tiny-progress"><i style={{width:`${items.length?done/items.length*100:0}%`}}/></div></div><button className="text-button" onClick={()=>onEditGroup(id)}>Open <small>เปิด</small></button></div>}
