import React,{useMemo,useState} from 'react'
import { Lightbulb, Plus, CalendarClock, ArrowRight, CheckCircle2 } from '../icons.jsx'
import { Badge, Button, Empty, Modal, PageIntro, PriorityGuide, SelectMenu } from '../components/UI.jsx'
import { fmtDate, rolePlanner, statusLabel } from '../lib/utils.js'

export default function Opportunities({profile,machines,opportunities,onSave,onCreateTPM,onUpdateStatus}){
  const [open,setOpen]=useState(false),[status,setStatus]=useState('open'),[form,setForm]=useState({machine_id:'',category:'reliability',title:'',details:'',expected_benefit:'',priority:'B',target_date:''}),[saving,setSaving]=useState(false)
  const rows=useMemo(()=>opportunities.filter(o=>status==='all'||(status==='open'?!['completed','rejected'].includes(o.status):o.status===status)).slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)),[opportunities,status])
  const submit=async()=>{if(!form.title.trim())return alert('Please enter title / กรุณาระบุหัวข้อ');setSaving(true);try{await onSave(form);setOpen(false);setForm({machine_id:'',category:'reliability',title:'',details:'',expected_benefit:'',priority:'B',target_date:''})}finally{setSaving(false)}}
  return <>
    <PageIntro title="Maintenance Opportunity" th="โอกาสปรับปรุงงานซ่อมบำรุง" description="Capture reliability, safety, cost and maintainability ideas, then convert them into real work. · เก็บไอเดียแล้วแปลงเป็น TPM / Improvement"><Button icon={Plus} onClick={()=>setOpen(true)}>New Opportunity <small>เพิ่มโอกาส</small></Button></PageIntro>
    <section className="compact-filter-bar"><SelectMenu value={status} onChange={setStatus} options={[{value:'open',label:'Active',sub:'กำลังติดตาม'},{value:'all',label:'All',sub:'ทั้งหมด'},{value:'review',label:'Review',sub:'ตรวจสอบ'},{value:'planned',label:'Planned',sub:'วางแผนแล้ว'},{value:'in_progress',label:'In Progress',sub:'กำลังทำ'},{value:'completed',label:'Completed',sub:'เสร็จแล้ว'}]}/></section>
    <div className="opportunity-grid">{rows.length?rows.map(o=><article className="opportunity-card" key={o.id}><header><div className="opportunity-icon"><Lightbulb/></div><div className="grow"><span>{o.category}</span><h3>{o.title}</h3></div><Badge tone={o.priority==='A'?'red':o.priority==='B'?'amber':'neutral'}>P-{o.priority}</Badge></header>{o.details&&<p>{o.details}</p>}{o.expected_benefit&&<div className="benefit-box"><span>Expected Benefit <small>ผลที่คาดหวัง</small></span><b>{o.expected_benefit}</b></div>}<div className="opportunity-meta"><span>{o.machines?.machine_no||'General IJ'}</span><span><CalendarClock size={14}/>{fmtDate(o.target_date)}</span><Badge tone={o.status==='completed'?'green':'blue'}>{statusLabel(o.status)}</Badge></div><footer>{rolePlanner(profile.role)&&!o.converted_job_id&&<Button size="sm" variant="soft" icon={ArrowRight} onClick={()=>onCreateTPM(o)}>Create TPM <small>แปลงเป็น TPM</small></Button>}{rolePlanner(profile.role)&&o.status!=='completed'&&<Button size="sm" variant="ghost" icon={CheckCircle2} onClick={()=>onUpdateStatus(o,'completed')}>Complete <small>เสร็จแล้ว</small></Button>}</footer></article>):<Empty title="No opportunity yet" text="ยังไม่มี Opportunity"/>}</div>
    <Modal open={open} onClose={()=>setOpen(false)} eyebrow="CONTINUOUS IMPROVEMENT" title="New Maintenance Opportunity" subtitle="เพิ่มโอกาสปรับปรุง" footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel · ยกเลิก</Button><Button loading={saving} onClick={submit}>Save · บันทึก</Button></>}><PriorityGuide compact/><div className="form-grid"><label>Machine <small>เครื่อง (ถ้ามี)</small><SelectMenu searchable value={form.machine_id} onChange={v=>setForm({...form,machine_id:v})} options={[{value:'',label:'Department / Not specified',sub:'ทั้งแผนก'},...machines.map(m=>({value:m.id,label:m.machine_no,sub:m.machine_name||'เครื่องจักร'}))]}/></label><label>Category <small>ประเภทโอกาส</small><SelectMenu value={form.category} onChange={v=>setForm({...form,category:v})} options={[{value:'reliability',label:'Reliability',sub:'ความเชื่อถือได้'},{value:'safety',label:'Safety',sub:'ความปลอดภัย'},{value:'quality',label:'Quality',sub:'คุณภาพ'},{value:'cost',label:'Cost',sub:'ลดต้นทุน'},{value:'energy',label:'Energy',sub:'พลังงาน'},{value:'maintainability',label:'Maintainability',sub:'ความง่ายในการบำรุงรักษา'},{value:'improvement',label:'Improvement',sub:'ปรับปรุงทั่วไป'}]}/></label><label className="span-2">Title <small>หัวข้อ</small><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="span-2">Details <small>รายละเอียด</small><textarea rows="3" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><label className="span-2">Expected Benefit <small>ผลที่คาดหวัง</small><input value={form.expected_benefit} onChange={e=>setForm({...form,expected_benefit:e.target.value})}/></label><label>Priority <small>ระดับความสำคัญ</small><SelectMenu value={form.priority} onChange={v=>setForm({...form,priority:v})} options={[{value:'A',label:'A — Critical',sub:'วิกฤต / จัดการทันที'},{value:'B',label:'B — Important',sub:'สำคัญ / ควรแก้เร็ว'},{value:'C',label:'C — Routine',sub:'ทั่วไป / วางแผนทำ'}]}/></label><label>Target Date <small>วันที่เป้าหมาย</small><input type="date" value={form.target_date} onChange={e=>setForm({...form,target_date:e.target.value})}/></label></div></Modal>
  </>
}
