import React,{useMemo,useState} from 'react'
import { CalendarClock, Timer, Activity, ShieldCheck, AlertTriangle, PlusCircle } from '../icons.jsx'
import { Badge, Button, Empty, PageIntro } from '../components/UI.jsx'
import { fmtDate } from '../lib/utils.js'

export default function PMStandard({plans,schedule,onCreateTPM}){
 const [tab,setTab]=useState('standard');const overdue=useMemo(()=>schedule.filter(s=>!s.completed_at&&s.status!=='completed'&&new Date(`${s.due_date}T23:59:59`)<new Date()),[schedule]);const dueSoon=useMemo(()=>schedule.filter(s=>!s.completed_at&&s.status!=='completed'&&new Date(s.due_date)>=new Date()&&new Date(s.due_date)<=new Date(Date.now()+14*86400000)),[schedule])
 return <><PageIntro title="PM Standard & Schedule" th="มาตรฐานและตาราง PM" description="Build preventive standards from repeated TPM, repair and defect data. · ค่อย ๆ สร้างมาตรฐานจากข้อมูลที่เกิดซ้ำจริง"><div className="segment compact-segment"><button className={tab==='standard'?'active':''} onClick={()=>setTab('standard')}>PM Standard <small>มาตรฐาน</small></button><button className={tab==='due'?'active':''} onClick={()=>setTab('due')}>Due / Overdue <small>ถึงรอบ / เกินกำหนด</small></button></div></PageIntro>{tab==='standard'?<div className="pm-grid-pro">{plans.length?plans.map(p=><article className="pm-card-pro" key={p.id}><div className="pm-top"><div className="machine-code">{p.machines?.machine_no||'-'}</div><Badge tone="green">Active</Badge></div><h3>{p.title}</h3><p>{p.description||'No description · ไม่มีรายละเอียด'}</p><div className="pm-stats"><div><CalendarClock/><span>Frequency<small>ความถี่</small></span><b>{p.frequency}</b></div><div><Timer/><span>Standard time<small>เวลามาตรฐาน</small></span><b>{p.std_minutes||0} min</b></div><div><Activity/><span>Start<small>เริ่มใช้</small></span><b>{fmtDate(p.start_date)}</b></div><div><ShieldCheck/><span>Status<small>สถานะ</small></span><b>{p.is_active?'Active':'Inactive'}</b></div></div></article>):<Empty title="No PM Standard yet" text="ยังไม่มี PM Standard — ใช้ TPM เก็บข้อมูลจริงก่อน"/>}</div>:<div className="pm-due-stack"><section className="summary-strip"><span className="bad"><b>{overdue.length}</b> Overdue <small>เกินกำหนด</small></span><span className="warn"><b>{dueSoon.length}</b> Due ≤ 14 days <small>ใกล้ถึงรอบ</small></span><span><b>{schedule.length}</b> Total schedule <small>ทั้งหมด</small></span></section>{[...overdue,...dueSoon].length?[...overdue,...dueSoon].map(s=><article className="pm-due-row" key={s.id}><div className={`due-indicator ${overdue.includes(s)?'overdue':'soon'}`}><AlertTriangle/></div><div className="grow"><h3>{s.machine_no_snapshot} · {s.plan_title_snapshot}</h3><p>Due {fmtDate(s.due_date)} · Standard {s.std_minutes_snapshot||0} min</p></div><Badge tone={overdue.includes(s)?'red':'amber'}>{overdue.includes(s)?'Overdue · เกินกำหนด':'Due Soon · ใกล้ถึงรอบ'}</Badge>{onCreateTPM&&<Button size="sm" variant="soft" icon={PlusCircle} onClick={()=>onCreateTPM(s)}>Add to TPM <small>ใส่แผน</small></Button>}</article>):<Empty title="No PM due / overdue" text="ไม่มี PM ถึงรอบหรือเกินกำหนด"/>}</div>}</>
}
