import React,{useMemo,useState} from 'react'
import { Printer, Download, FileBarChart, Wrench, CalendarCheck2, AlertTriangle, Gauge, Activity, Clock3, CheckCircle2, Filter, ChevronDown } from '../icons.jsx'
import { Button, Empty, PageIntro, SelectMenu } from '../components/UI.jsx'
import { isoDate, addDays, fmtDate, machineGroup } from '../lib/utils.js'
import { periodRepairMetrics,tpmMetrics,defectMetrics,topLossMachines } from '../lib/kpi.js'

export default function Reports({machines,jobs,repairs,findings,inspections,kpiSettings}){
  const [from,setFrom]=useState(isoDate(addDays(new Date(),-30))),[to,setTo]=useState(isoDate()),[type,setType]=useState('all'),[group,setGroup]=useState(''),[detailOpen,setDetailOpen]=useState(true)
  const selectedMachines=useMemo(()=>machines.filter(m=>!group||machineGroup(m.machine_no)===group),[machines,group]);const ids=new Set(selectedMachines.map(m=>m.id))
  const periodRepairs=repairs.filter(r=>(ids.has(r.machine_id)||selectedMachines.some(m=>m.machine_no===r.machine_no_snapshot))&&inRange(r.started_at,from,to))
  const periodJobs=jobs.filter(j=>ids.has(j.machine_id)&&inRange(j.planned_date,from,to)&&['completed','partial'].includes(j.job_status))
  const periodFindings=findings.filter(f=>ids.has(f.machine_id)&&inRange(f.created_at,from,to));const periodInspections=inspections.filter(i=>ids.has(i.machine_id)&&inRange(i.inspection_date||i.created_at,from,to))
  const cfg=kpiSettings?.find(x=>x.machine_no==null)||kpiSettings?.[0]||{};const repair=periodRepairMetrics({repairs:periodRepairs,machines:selectedMachines,from,to,hoursPerDay:cfg.hours_per_day||24});const tpm=tpmMetrics(jobs.filter(j=>ids.has(j.machine_id)),from,to),defect=defectMetrics(findings.filter(f=>ids.has(f.machine_id)),from,to),topLoss=topLossMachines(periodRepairs,5)
  const multiMachine=selectedMachines.length>1;const availabilityLabel=multiMachine?'Maintenance Efficiency':'Availability';const availabilityTh=multiMachine?'ประสิทธิภาพเวลาหลังหัก Breakdown Loss':'ความพร้อมใช้งานของเครื่อง';
  const show=k=>type==='all'||type===k
  const exportCsv=()=>{const rows=[['Date','Type','Machine','Title/Symptom','Detail/Action','Loss min','Status']];if(show('repair'))periodRepairs.forEach(r=>rows.push([r.started_at,'Repair',r.machine_no_snapshot,r.symptom,r.action_taken,r.loss_time_min,r.status]));if(show('tpm'))periodJobs.forEach(j=>rows.push([j.planned_date,'TPM/PM',j.machines?.machine_no||'',j.title,j.details||'',j.ij_tpm_executions?.[0]?.actual_stop_min||j.planned_stop_min,j.job_status]));if(show('inspection'))periodInspections.forEach(i=>rows.push([i.inspection_date,'Inspection',i.machines?.machine_no||'','Condition Inspection',i.note||'',0,i.overall_status]));if(show('defect'))periodFindings.forEach(f=>rows.push([f.created_at,'Defect',f.machines?.machine_no||'',f.finding,f.permanent_action||f.recommendation||'',0,f.status]));const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`IJ_Maintenance_Report_${from}_${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
  const summary=[
    `Repair records ${repair.breakdowns} jobs with ${repair.lossMin.toLocaleString()} min total loss.`,
    `TPM/PM completed ${tpm.completed}/${tpm.rows.length} jobs (${tpm.completion}%).`,
    `Defects created ${defect.created.length}; ${defect.closed} closed in the selected period.`
  ]
  return <>
    <PageIntro title="Maintenance Report" th="รายงานซ่อมบำรุง" description="Executive summary for Maintenance, Production and management. · สรุปข้อมูลให้หัวหน้าและฝ่ายผลิตอ่านง่าย"/>
    <section className="report-filter-panel no-print"><div className="report-filter-title"><Filter size={18}/><div><b>Report filters</b><small>ตัวกรองรายงาน</small></div></div><div className="report-filter-grid"><label>From <small>จากวันที่</small><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <small>ถึงวันที่</small><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Report type <small>ประเภทรายงาน</small><SelectMenu value={type} onChange={setType} options={[{value:'all',label:'All modules',sub:'ทั้งหมด'},{value:'tpm',label:'TPM / PM',sub:'งานป้องกัน'},{value:'repair',label:'Repair',sub:'งานซ่อม'},{value:'inspection',label:'Inspection',sub:'ตรวจสภาพ'},{value:'defect',label:'Defect',sub:'จุดผิดปกติ'}]}/></label><label>Machine group <small>กลุ่มเครื่อง</small><SelectMenu value={group} onChange={setGroup} options={[{value:'',label:'All IJ',sub:'ทั้งแผนก'},...[...new Set(machines.map(m=>machineGroup(m.machine_no)))].sort().map(g=>({value:g,label:g,sub:'กลุ่มเครื่อง'}))]}/></label></div><div className="report-actions"><Button icon={Printer} onClick={()=>window.print()}>Print / Save PDF <small>พิมพ์ / บันทึก PDF</small></Button><Button variant="ghost" icon={Download} onClick={exportCsv}>Export CSV</Button></div></section>
    <article className="executive-report-v5 printable-area">
      <header className="report-hero-v5"><div><p>IJ MAINTENANCE · UNIFIED SYSTEM</p><h1>Executive Maintenance Report</h1><span>รายงานสรุปสภาพเครื่องจักรและงานซ่อมบำรุง</span></div><div><b>{fmtDate(from)} — {fmtDate(to)}</b><span>{group||'All IJ Machines · เครื่อง IJ ทั้งหมด'}</span></div></header>
      <section className="report-kpi-grid-v5"><ReportKpi label={availabilityLabel} th={availabilityTh} value={`${repair.availability.toFixed(2)}%`} icon={Gauge}/><ReportKpi label="MTBF" th="ระยะห่างระหว่างการซ่อม" value={repair.mtbf!==null?`${repair.mtbf.toFixed(1)} h`:'N/A'} icon={Activity}/><ReportKpi label="MTTR" th="เวลาซ่อมเฉลี่ย" value={`${repair.mttr.toFixed(0)} min`} icon={Clock3}/><ReportKpi label="TPM Completion" th="ทำ TPM ตามแผน" value={`${tpm.completion}%`} icon={CheckCircle2}/><ReportKpi label="Repair Loss" th="Loss งานซ่อม" value={`${repair.lossMin.toLocaleString()} min`} icon={Wrench}/><ReportKpi label="Open Defect" th="Defect ค้าง" value={findings.filter(f=>ids.has(f.machine_id)&&f.status!=='closed').length} icon={AlertTriangle}/></section>
      <section className="report-summary-v5"><h2>Management Summary <small>สรุปสำหรับผู้บริหาร</small></h2><div>{summary.map((x,i)=><article key={x}><span>{i+1}</span><p>{x}<small>{i===0?`มีงานซ่อม ${repair.breakdowns} รายการ Loss รวม ${repair.lossMin.toLocaleString()} นาที`:i===1?`TPM/PM ทำเสร็จ ${tpm.completed}/${tpm.rows.length} งาน`:`สร้าง Defect ${defect.created.length} รายการ ปิดแล้ว ${defect.closed} รายการ`}</small></p></article>)}</div></section>
      <section className="report-two-col"><article className="report-panel"><h2>Top Loss Machines <small>เครื่องที่มี Loss สูง</small></h2>{topLoss.length?<div className="report-loss-list">{topLoss.map((x,i)=><div key={x.machine}><span>{i+1}</span><div className="grow"><b>{x.machine}</b><small>{x.topIssue} · {x.count} repairs</small><div><i style={{width:`${topLoss[0]?.loss?x.loss/topLoss[0].loss*100:0}%`}}/></div></div><strong>{x.loss.toLocaleString()} min</strong></div>)}</div>:<Empty/>}</article><article className="report-panel"><h2>Work Volume <small>ปริมาณงาน</small></h2><div className="work-volume-grid"><div><b>{periodJobs.length}</b><span>TPM / PM<small>งานที่เสร็จ</small></span></div><div><b>{periodRepairs.length}</b><span>Repair<small>งานซ่อม</small></span></div><div><b>{periodInspections.length}</b><span>Inspection<small>ตรวจสภาพ</small></span></div><div><b>{periodFindings.length}</b><span>Defect<small>จุดผิดปกติ</small></span></div></div></article></section>
      <button className="report-detail-toggle no-print" onClick={()=>setDetailOpen(v=>!v)}>{detailOpen?'Hide detailed records · ซ่อนรายละเอียด':'Show detailed records · แสดงรายละเอียด'} <ChevronDown className={detailOpen?'rotated':''} size={17}/></button>
      {detailOpen&&<div className="report-details-v5">
      {show('tpm')&&<ReportSection title="TPM / PM Completed" th="งาน TPM / PM ที่เสร็จแล้ว" icon={CalendarCheck2} rows={periodJobs.map(j=>({id:j.id,date:fmtDate(j.planned_date),machine:j.machines?.machine_no||'-',title:j.title,detail:j.ij_tpm_executions?.[0]?.result_summary||j.details||'-',meta:`${j.ij_tpm_executions?.[0]?.actual_stop_min??j.planned_stop_min} min`}))}/>} 
      {show('repair')&&<ReportSection title="Repair / Breakdown" th="งานซ่อม / เครื่องเสีย" icon={Wrench} rows={periodRepairs.map(r=>({id:r.id,date:fmtDate(r.started_at),machine:r.machine_no_snapshot,title:r.symptom,detail:`Cause: ${r.cause||'-'} · Action: ${r.action_taken||'-'}`,meta:`${r.loss_time_min||0} min loss`}))}/>} 
      {show('inspection')&&<ReportSection title="Condition Inspection" th="การตรวจสภาพเครื่อง" rows={periodInspections.map(i=>({id:i.id,date:fmtDate(i.inspection_date),machine:i.machines?.machine_no||'-',title:`Condition ${i.condition_score??'-'}%`,detail:i.note||i.overall_status,meta:i.inspector_name_snapshot||'-'}))}/>} 
      {show('defect')&&<ReportSection title="Defects / Follow-up" th="จุดผิดปกติ / งานติดตาม" icon={AlertTriangle} rows={periodFindings.map(f=>({id:f.id,date:fmtDate(f.created_at),machine:f.machines?.machine_no||'-',title:f.finding,detail:f.permanent_action||f.recommendation||f.temporary_action||'-',meta:f.status}))}/>} 
      </div>}
      <footer className="report-footer">Generated from IJ Maintenance System · MPR unified database</footer>
    </article>
  </>
}
function inRange(value,from,to){if(!value)return false;const d=new Date(String(value).length===10?`${value}T00:00:00`:value);return d>=new Date(`${from}T00:00:00`)&&d<=new Date(`${to}T23:59:59`)}
function ReportKpi({label,th,value,icon:Icon=FileBarChart}){return <div><Icon size={18}/><span>{label}</span><small>{th}</small><b>{value}</b></div>}
function ReportSection({title,th,icon:Icon=FileBarChart,rows}){return <section className="report-record-section"><header><Icon size={18}/><div><h2>{title}</h2><span>{th}</span></div><b>{rows.length}</b></header>{rows.length?<div className="report-record-list">{rows.slice(0,120).map(r=><article key={r.id}><div className="record-date">{r.date}</div><div className="record-machine">{r.machine}</div><div className="record-body"><b>{r.title}</b><p>{r.detail}</p></div><div className="record-meta">{r.meta}</div></article>)}</div>:<Empty/>}</section>}
