import React,{useMemo,useState} from 'react'
import { PackageSearch, Plus, Search, Clock3, Wrench, RefreshCcw, ChevronDown } from '../icons.jsx'
import { Badge, Button, Empty, Modal, PageIntro, SelectMenu } from '../components/UI.jsx'
import { fmtDateTime, statusLabel, shortStatusLabel } from '../lib/utils.js'

const STATUSES=['new','review','ready','sent','follow_up','closed']
export default function SpareParts({profile,machines,requests,onSave,onUpdateStatus}){
  const [q,setQ]=useState(''),[status,setStatus]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[updating,setUpdating]=useState('')
  const [form,setForm]=useState({machine_id:'',requested_part_name:'',requested_part_no:'',requested_specification:'',requested_reason:'',quantity:1,unit:'pcs',urgency:'planned',remark:''})
  const rows=useMemo(()=>requests.filter(r=>!status||r.status===status).filter(r=>!q||[r.part_name,r.requested_part_name,r.requested_part_no,r.machine?.machine_no,r.requested_reason].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase()))),[requests,status,q])
  const submit=async()=>{if(!form.requested_part_name.trim()||!form.requested_reason.trim())return alert('Please enter part name and reason / กรุณาระบุชื่ออะไหล่และเหตุผล');setSaving(true);try{await onSave(form);setOpen(false);setForm({machine_id:'',requested_part_name:'',requested_part_no:'',requested_specification:'',requested_reason:'',quantity:1,unit:'pcs',urgency:'planned',remark:''})}finally{setSaving(false)}}
  const canManage=r=>profile.role==='admin'||profile.role==='supervisor'||r.requester_profile_id===profile.id
  const update=async(r,next)=>{if(next===r.status)return;setUpdating(r.id);try{await onUpdateStatus(r,next)}finally{setUpdating('')}}
  return <>
    <PageIntro title="Spare Parts Requests" th="คำขออะไหล่" description="Track request status from New to Closed using the same MPR Maintenance database. · ติดตามสถานะคำขออะไหล่ในฐานเดียวกัน">
      <Button icon={Plus} onClick={()=>setOpen(true)}>New Request <small>ขออะไหล่</small></Button>
    </PageIntro>
    <section className="spare-toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search part / machine · ค้นหาอะไหล่ / เครื่อง"/></div><SelectMenu value={status} onChange={setStatus} options={[{value:'',label:'All statuses',sub:'ทุกสถานะ'},...STATUSES.map(x=>{const [en,th]=statusLabel(x).split(' · ');return {value:x,label:en,sub:th||''}})]}/></section>
    <section className="spare-summary-v5"><Summary icon={PackageSearch} en="Total requests" th="ทั้งหมด" value={requests.length}/><Summary icon={Clock3} en="Open requests" th="ยังไม่ปิด" value={requests.filter(r=>r.status!=='closed').length}/><Summary icon={Wrench} en="Urgent open" th="เร่งด่วน" value={requests.filter(r=>r.urgency==='urgent'&&r.status!=='closed').length}/></section>
    <div className="spare-list-v5">{rows.length?rows.map(r=><article className={`spare-row-v5 ${r.urgency==='urgent'?'urgent':''}`} key={r.id}>
      <div className="spare-main"><div className="spare-topline"><span className="machine-pill">{r.machine?.machine_no||'General IJ'}</span><Badge tone={r.urgency==='urgent'?'red':r.urgency==='improvement'?'amber':'neutral'}>{r.urgency}</Badge></div><h3>{r.part_name||r.requested_part_name}</h3><p>{r.specification||r.requested_specification||'No specification · ไม่ระบุ Spec'}</p><div className="spare-request-meta"><span><b>{r.quantity}</b> {r.unit}</span><span>{r.requester_name_snapshot}</span><span>{fmtDateTime(r.created_at)}</span></div></div>
      <div className="spare-reason-v5"><span>Reason <small>เหตุผล / จุดใช้งาน</small></span><p>{r.requested_reason}</p>{r.remark&&<em>{r.remark}</em>}</div>
      <div className="spare-status-control"><span>Request status <small>สถานะคำขอ</small></span>{canManage(r)?<div className="status-select-wrap"><SelectMenu compact value={r.status} disabled={updating===r.id} onChange={v=>update(r,v)} options={STATUSES.map(x=>{const [en,th]=statusLabel(x).split(' · ');return {value:x,label:en,sub:th||''}})}/>{updating===r.id&&<RefreshCcw className="spin status-spinner" size={16}/>}</div>:<Badge tone={r.status==='closed'?'green':r.status==='follow_up'?'amber':'blue'}>{shortStatusLabel(r.status)}</Badge>}<small className="status-help">New → Review → Ready → Sent → Follow-up → Closed</small></div>
    </article>):<Empty/>}</div>
    <Modal open={open} onClose={()=>setOpen(false)} eyebrow="MPR SPARE REQUEST" title="Create Spare Request" subtitle="สร้างคำขออะไหล่" footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel · ยกเลิก</Button><Button loading={saving} onClick={submit}>Submit Request · ส่งคำขอ</Button></>}><div className="form-grid"><label>Machine <small>เครื่อง</small><SelectMenu value={form.machine_id} onChange={v=>setForm({...form,machine_id:v})} searchable options={[{value:'',label:'General / Not specified',sub:'ไม่ระบุเครื่อง'},...machines.map(m=>({value:m.id,label:m.machine_no,sub:m.machine_name||'เครื่องจักร'}))]}/></label><label>Urgency <small>ความเร่งด่วน</small><SelectMenu value={form.urgency} onChange={v=>setForm({...form,urgency:v})} options={[{value:'planned',label:'Planned',sub:'ตามแผน'},{value:'urgent',label:'Urgent',sub:'เร่งด่วน'},{value:'improvement',label:'Improvement',sub:'ปรับปรุง'}]}/></label><label>Part name <small>ชื่ออะไหล่</small><input value={form.requested_part_name} onChange={e=>setForm({...form,requested_part_name:e.target.value})}/></label><label>Part No.<input value={form.requested_part_no} onChange={e=>setForm({...form,requested_part_no:e.target.value})}/></label><label className="span-2">Specification <small>สเปก</small><input value={form.requested_specification} onChange={e=>setForm({...form,requested_specification:e.target.value})}/></label><label>Quantity <small>จำนวน</small><input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unit <small>หน่วย</small><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label className="span-2">Reason / application point <small>เหตุผล / จุดใช้งาน</small><textarea rows="3" value={form.requested_reason} onChange={e=>setForm({...form,requested_reason:e.target.value})}/></label><label className="span-2">Remark <small>หมายเหตุ</small><textarea rows="2" value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})}/></label></div></Modal>
  </>
}
function Summary({icon:Icon,en,th,value}){return <article><Icon/><div><span>{en}</span><small>{th}</small></div><b>{value}</b></article>}
