import React,{useEffect,useState} from 'react'
import { Modal,Button,SelectMenu } from './UI.jsx'
import { fmtDate } from '../lib/utils.js'

export default function ExecutionModal({job,open,onClose,onFinish}){
 const [saving,setSaving]=useState(false),[form,setForm]=useState({result_summary:'',actual_stop_min:0,completion_status:'completed',parts_used:'',execution_note:'',abnormal_found:false,follow_up_required:false})
 useEffect(()=>{if(open)setForm({result_summary:'',actual_stop_min:job?.planned_stop_min||0,completion_status:'completed',parts_used:'',execution_note:'',abnormal_found:false,follow_up_required:false})},[open,job])
 if(!job)return null
 const submit=async()=>{setSaving(true);try{await onFinish(job,form);onClose()}finally{setSaving(false)}}
 return <Modal open={open} onClose={onClose} title={`Complete Job · ${job.machines?.machine_no||''}`} subtitle="บันทึกผลและปิดงาน" eyebrow="WORK RESULT" footer={<><span className="muted">Plan date · วันที่แผน: {fmtDate(job.planned_date)}</span><div className="footer-actions"><Button variant="ghost" onClick={onClose}>Cancel · ยกเลิก</Button><Button loading={saving} onClick={submit}>Save & Close · บันทึกและปิด</Button></div></>}>
   <div className="form-grid"><label className="span-2">Work result <small>ผลการทำงาน</small><textarea rows="4" value={form.result_summary} onChange={e=>setForm({...form,result_summary:e.target.value})} placeholder="What was found and what was done / สิ่งที่พบและสิ่งที่ดำเนินการ"/></label><label>Actual stop (min) <small>เวลาหยุดจริง</small><input type="number" min="0" value={form.actual_stop_min} onChange={e=>setForm({...form,actual_stop_min:e.target.value})}/></label><label>Completion <small>ผลการปิดงาน</small><SelectMenu value={form.completion_status} onChange={v=>setForm({...form,completion_status:v})} options={[{value:'completed',label:'Completed',sub:'เสร็จแล้ว'},{value:'partial',label:'Partial',sub:'เสร็จบางส่วน'}]}/></label><label className="span-2">Parts used <small>อะไหล่ที่ใช้</small><input value={form.parts_used} onChange={e=>setForm({...form,parts_used:e.target.value})} placeholder="If any / ถ้ามี"/></label><label className="span-2">Additional note <small>หมายเหตุเพิ่มเติม</small><textarea rows="3" value={form.execution_note} onChange={e=>setForm({...form,execution_note:e.target.value})}/></label><label className="check-card"><input type="checkbox" checked={form.abnormal_found} onChange={e=>setForm({...form,abnormal_found:e.target.checked})}/><span><b>Abnormal found</b><small>พบความผิดปกติระหว่างงาน</small></span></label><label className="check-card"><input type="checkbox" checked={form.follow_up_required} onChange={e=>setForm({...form,follow_up_required:e.target.checked})}/><span><b>Follow-up required</b><small>ต้องติดตามต่อหลังงาน</small></span></label></div>
 </Modal>
}
