import React, { useState } from 'react'
import { Wrench, Shield, Hash, LockKeyhole, ArrowRight } from '../icons.jsx'
import { edgeLogin } from '../lib/supabase.js'
import { Button } from './UI.jsx'

export default function Login({ onSuccess }) {
  const [mode,setMode]=useState('employee'),[employeeCode,setEmployeeCode]=useState(''),[username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  const submit=async(e)=>{e.preventDefault();setError('');setLoading(true);try{if(mode==='employee')await edgeLogin('employee-code-login',{employeeCode:employeeCode.trim()});else await edgeLogin('admin-login',{username:username.trim(),password});await onSuccess()}catch(err){setError(err.message||'Sign in failed · เข้าสู่ระบบไม่สำเร็จ')}finally{setLoading(false)}}
  return <main className="login-page"><section className="login-visual"><div className="login-visual-inner"><div className="brand brand-login"><div className="brand-logo">IJ</div><div><b>IJ Maintenance</b><span>MPR unified database</span></div></div><div className="login-copy"><span className="hero-chip">TPM · PM · Repair · Inspection · KPI</span><h1>One maintenance system<br/>for the whole IJ department</h1><p>ระบบซ่อมบำรุง IJ แบบรวมศูนย์ วางแผน TPM หลายเครื่อง เชื่อม Repair History, Condition Inspection, Spare Parts, KPI และ Executive Report ในฐานข้อมูลเดียว</p></div><div className="login-feature-grid"><div><strong>Multi-machine TPM</strong><span>1 plan · หลายเครื่อง</span></div><div><strong>Machine Timeline</strong><span>Repair + TPM + Inspection</span></div><div><strong>MPR Database</strong><span>ฐานข้อมูลเดียวกัน</span></div></div></div></section><section className="login-form-zone"><form className="login-card-pro" onSubmit={submit}><div className="login-icon"><Wrench size={24}/></div><p className="eyebrow">WELCOME BACK</p><h2>Sign in</h2><p className="muted">เข้าสู่ระบบด้วยบัญชี MPR Maintenance เดิม</p><div className="segment"><button type="button" className={mode==='employee'?'active':''} onClick={()=>setMode('employee')}><Hash size={16}/>Employee ID <small>รหัสพนักงาน</small></button><button type="button" className={mode==='admin'?'active':''} onClick={()=>{setMode('admin');if(!username)setUsername('admin')}}><Shield size={16}/>Admin</button></div>{mode==='employee'?<label className="input-label">Employee ID <small>รหัสพนักงาน</small><div className="input-icon"><Hash size={18}/><input inputMode="numeric" autoComplete="username" value={employeeCode} onChange={e=>setEmployeeCode(e.target.value)} placeholder="e.g. 680470" required/></div></label>:<><label className="input-label">Username<div className="input-icon"><Shield size={18}/><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></div></label><label className="input-label">Password <small>รหัสผ่าน</small><div className="input-icon"><LockKeyhole size={18}/><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div></label></>}{error&&<div className="login-error">{error}</div>}<Button className="login-submit" loading={loading} type="submit">Sign in <small>เข้าสู่ระบบ</small><ArrowRight size={18}/></Button><small className="login-foot">IJ Maintenance · Unified System v12.4</small></form></section></main>
}
