import React, { useEffect, useMemo, useState } from 'react'
import { Plus, Trash2, Copy, CalendarDays, Users, Factory, ShieldCheck } from '../icons.jsx'
import { Modal, Button, Badge, PriorityGuide, SelectMenu } from './UI.jsx'
import { nextSunday, uid } from '../lib/utils.js'

const blankRow = () => ({ key: uid(), id:null, machine_id:'', work_type:'tpm_added', priority:'B', planned_stop_min:60, title:'', details:'', reason_trigger:'', need_machine_stop:true })

export default function PlanBuilder({ open, onClose, machines, technicians, editingGroup, sourceContext, initialDate='', onSave }) {
  const [saving,setSaving]=useState(false),[meta,setMeta]=useState({ name:'', date:nextSunday(), time:'', note:'', production_status:'waiting', manager_status:'waiting' }),[rows,setRows]=useState([blankRow()]),[assignees,setAssignees]=useState([])
  useEffect(()=>{if(!open)return;if(editingGroup?.length){const first=editingGroup[0];setMeta({ name:first.plan_group_name||'', date:first.planned_date||nextSunday(), time:(first.planned_start_time||'').slice(0,5), note:first.plan_group_note||'', production_status:first.production_status||'waiting', manager_status:first.manager_status||'waiting' });setRows(editingGroup.map(j=>({ key:uid(), id:j.id, machine_id:j.machine_id, work_type:j.work_type, priority:j.priority, planned_stop_min:j.planned_stop_min, title:j.title, details:j.details||'', reason_trigger:j.reason_trigger||'', need_machine_stop:j.need_machine_stop })));setAssignees([...new Set(editingGroup.flatMap(j=>(j.ij_tpm_job_assignees||[]).map(a=>a.profile_id)))])}else if(sourceContext){const src=sourceContext.data||{},prefill=sourcePrefill(sourceContext.type,src);setMeta({ name:prefill.name, date:prefill.date||initialDate||nextSunday(), time:'', note:prefill.note||'', production_status:'waiting', manager_status:'waiting' });setRows([{...blankRow(),...prefill.row}]);setAssignees([])}else{setMeta({ name:'', date:initialDate||nextSunday(), time:'', note:'', production_status:'waiting', manager_status:'waiting' });setRows([blankRow()]);setAssignees([])}},[open,editingGroup,sourceContext,initialDate])
  const totalStop=useMemo(()=>rows.reduce((s,r)=>s+(Number(r.planned_stop_min)||0),0),[rows]),machineCount=useMemo(()=>new Set(rows.map(r=>r.machine_id).filter(Boolean)).size,[rows])
  const update=(key,patch)=>setRows(rs=>rs.map(r=>r.key===key?{...r,...patch}:r)),add=()=>setRows(rs=>[...rs,blankRow()]),duplicate=row=>setRows(rs=>[...rs,{...row,key:uid(),id:null}]),remove=key=>setRows(rs=>rs.length===1?rs:rs.filter(r=>r.key!==key)),toggleAssignee=id=>setAssignees(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id])
  const submit=async()=>{if(!meta.date)return alert('Select plan date / กรุณาเลือกวันที่');if(rows.some(r=>!r.machine_id||!r.title.trim()))return alert('Complete machine and work title for every row / กรุณาเลือกเครื่องและระบุงานให้ครบ');setSaving(true);try{await onSave({meta,rows,assignees});onClose()}finally{setSaving(false)}}
  return <Modal open={open} onClose={onClose} wide eyebrow="TPM PLAN BUILDER" title={editingGroup?.length?'Edit Multi-machine TPM Plan':'Create Multi-machine TPM Plan'} subtitle={editingGroup?.length?'แก้ไขแผน TPM':'สร้างแผน TPM หลายเครื่อง'} footer={<><div className="builder-summary"><Badge tone="blue">{rows.length} jobs · งาน</Badge><Badge tone="neutral">{machineCount} machines · เครื่อง</Badge><Badge tone="amber">Stop {totalStop} min</Badge></div><div className="footer-actions"><Button variant="ghost" onClick={onClose}>Cancel · ยกเลิก</Button><Button loading={saving} onClick={submit}>Save Plan · บันทึกแผน</Button></div></>}>
    <div className="builder-layout"><aside className="builder-sidebar"><div className="section-label"><CalendarDays size={17}/>Plan Information <small>ข้อมูลแผน</small></div><label>Plan name <small>ชื่อแผน</small><input value={meta.name} onChange={e=>setMeta({...meta,name:e.target.value})} placeholder="e.g. Sunday TPM · 650T group"/></label><div className="two-col"><label>Date <small>วันที่</small><input type="date" value={meta.date} onChange={e=>setMeta({...meta,date:e.target.value})}/></label><label>Start time <small>เวลาเริ่ม</small><input type="time" value={meta.time} onChange={e=>setMeta({...meta,time:e.target.value})}/></label></div><label>Plan note <small>หมายเหตุรวม</small><textarea rows="3" value={meta.note} onChange={e=>setMeta({...meta,note:e.target.value})}/></label><div className="section-label"><Factory size={17}/>Production Confirmation <small>ยืนยันจาก Production</small></div><SelectMenu value={meta.production_status} onChange={v=>setMeta({...meta,production_status:v})} options={[{value:'waiting',label:'Waiting',sub:'รอยืนยัน'},{value:'confirmed',label:'Confirmed',sub:'ยืนยันแล้ว'},{value:'not_required',label:'Not Required',sub:'ไม่ต้องยืนยัน'},{value:'change_requested',label:'Change Requested',sub:'ขอเปลี่ยนแผน'},{value:'rejected',label:'Rejected',sub:'ไม่อนุมัติ'}]}/><div className="section-label"><ShieldCheck size={17}/>Manager Approval <small>อนุมัติผู้จัดการ</small></div><SelectMenu value={meta.manager_status} onChange={v=>setMeta({...meta,manager_status:v})} options={[{value:'waiting',label:'Waiting',sub:'รออนุมัติ'},{value:'approved',label:'Approved',sub:'อนุมัติแล้ว'},{value:'not_required',label:'Not Required',sub:'ไม่ต้องอนุมัติ'},{value:'rejected',label:'Rejected',sub:'ไม่อนุมัติ'}]}/><div className="section-label"><Users size={17}/>Assigned Technicians <small>ผู้รับผิดชอบ</small></div><div className="assignee-grid">{technicians.map(t=><button type="button" key={t.id} onClick={()=>toggleAssignee(t.id)} className={assignees.includes(t.id)?'assignee active':'assignee'}><span className="mini-avatar">{t.full_name?.slice(0,1)}</span><span><b>{t.full_name}</b><small>{t.employee_code||''} {t.shift||''}</small></span></button>)}</div></aside>
      <section className="builder-main"><PriorityGuide compact/><div className="builder-main-head"><div><p className="eyebrow">MACHINE JOBS</p><h4>Machine work list</h4><span>รายการเครื่องและงาน · เพิ่มหลายเครื่องในแผนเดียว</span></div><Button variant="soft" icon={Plus} onClick={add}>Add Machine <small>เพิ่มเครื่อง</small></Button></div><div className="machine-job-list">{rows.map((row,i)=><article className="machine-job-card" key={row.key}><div className="machine-job-index">{String(i+1).padStart(2,'0')}</div><div className="machine-job-body"><div className="machine-grid-top"><label>Machine <small>เครื่อง</small><SelectMenu searchable value={row.machine_id} onChange={v=>update(row.key,{machine_id:v})} options={[{value:'',label:'Select machine',sub:'เลือกเครื่อง'},...machines.map(m=>({value:m.id,label:m.machine_no,sub:m.area||m.machine_name||'เครื่องจักร'}))]}/></label><label>Work type <small>ประเภทงาน</small><SelectMenu value={row.work_type} onChange={v=>update(row.key,{work_type:v})} options={[{value:'tpm_added',label:'TPM Added',sub:'งานตามสภาพ'},{value:'pm_scheduled',label:'PM Scheduled',sub:'PM ตามรอบ'},{value:'follow_up',label:'Follow-up',sub:'งานติดตาม'},{value:'improvement',label:'Improvement',sub:'งานปรับปรุง'},{value:'emergency_repair',label:'Repair',sub:'งานซ่อม'}]}/></label><label>Priority <small>ระดับ</small><SelectMenu value={row.priority} onChange={v=>update(row.key,{priority:v})} options={[{value:'A',label:'A — Critical',sub:'วิกฤต / ทำทันที'},{value:'B',label:'B — Important',sub:'สำคัญ / ควรแก้เร็ว'},{value:'C',label:'C — Routine',sub:'ทั่วไป / วางแผนทำ'}]}/></label><label>Stop (min) <small>เวลาหยุด</small><input type="number" min="0" value={row.planned_stop_min} onChange={e=>update(row.key,{planned_stop_min:e.target.value})}/></label></div><label>Work title <small>งานที่จะทำ</small><input value={row.title} onChange={e=>update(row.key,{title:e.target.value})} placeholder="e.g. Inspect and replace deteriorated air tubes"/></label><div className="two-col"><label>Details <small>รายละเอียด</small><textarea rows="2" value={row.details} onChange={e=>update(row.key,{details:e.target.value})}/></label><label>Reason / Trigger <small>เหตุผล / ที่มา</small><textarea rows="2" value={row.reason_trigger} onChange={e=>update(row.key,{reason_trigger:e.target.value})}/></label></div><div className="row-footer"><label className="switch-line"><input type="checkbox" checked={row.need_machine_stop} onChange={e=>update(row.key,{need_machine_stop:e.target.checked})}/><span className="switch"/><span>Machine stop required <small>ต้องหยุดเครื่อง</small></span></label><div className="inline-actions"><button type="button" onClick={()=>duplicate(row)}><Copy size={16}/>Duplicate <small>คัดลอก</small></button><button type="button" className="danger-link" onClick={()=>remove(row.key)}><Trash2 size={16}/>Remove <small>ลบ</small></button></div></div></div></article>)}</div></section>
    </div>
  </Modal>
}
function sourcePrefill(type,src){if(type==='repair')return {name:`Follow-up ${src.machine_no_snapshot||''}`,row:{machine_id:src.machine_id||'',work_type:'follow_up',priority:'A',title:`Follow-up: ${src.symptom||'Repair finding'}`,details:src.action_taken||'',reason_trigger:`From Repair History ${src.record_no||''} | ${src.cause||''}`}};if(type==='finding')return {name:`Defect Follow-up ${src.machines?.machine_no||''}`,row:{machine_id:src.machine_id||'',work_type:'follow_up',priority:src.priority||'A',title:`Corrective: ${src.finding||'Defect'}`,details:src.permanent_action||src.recommendation||'',reason_trigger:`From Defect/Finding | ${src.risk||''}`}};if(type==='opportunity')return {name:`Improvement ${src.machines?.machine_no||'IJ'}`,row:{machine_id:src.machine_id||'',work_type:'improvement',priority:src.priority||'B',title:src.title||'Improvement',details:src.details||src.expected_benefit||'',reason_trigger:`Maintenance Opportunity | ${src.expected_benefit||''}`}};if(type==='pm')return {name:`PM Due ${src.machine_no_snapshot||''}`,date:src.due_date||'',row:{machine_id:src.machine_id||'',work_type:'pm_scheduled',priority:'B',planned_stop_min:src.std_minutes_snapshot||60,title:src.plan_title_snapshot||'PM Scheduled',details:'',reason_trigger:`PM Due ${src.due_date||''}`}};return {name:'',row:{}}}
